apiVersion: v1
kind: ConfigMap
metadata:
  name: codenova-config
  namespace: production
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "postgres.production.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "codenova_prod"
  FRONTEND_URL: "http://a42f7070983a145f98a3edeb7c98a215-1394932142.ap-south-1.elb.amazonaws.com"
