apiVersion: v1
kind: Secret
metadata:
  name: codenova-secrets
  namespace: production
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASSWORD: "supersecret_db_password"
  JWT_SECRET: "super_secret_jwt_signature_key"
